name: Python CI

on:
  push:
    branches:
      - main  # Le workflow s'exécutera lors d'un push sur la branche main
  pull_request:
    branches:
      - main  # Le workflow s'exécutera lors de la création d'une pull request sur la branche main

jobs:
  test:
    runs-on: ubuntu-latest  # Utilise une machine virtuelle Ubuntu pour exécuter le workflow

    steps:
      # Étape 1 : Vérifier le code source
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Installer Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Spécifie la version de Python à utiliser

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assure-toi d'avoir un fichier requirements.txt avec les dépendances nécessaires

      # Étape 4 : Exécuter les tests
      - name: Run tests
        run: |
          python -m unittest discover  # Exécute tous les tests dans le répertoire actuel
